# Generated by Django 3.2.8 on 2022-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticiascad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo da notícia')),
                ('autenticidade', models.CharField(max_length=10, verbose_name='Verdadeiro ou Falso?')),
                ('linknews', models.URLField(verbose_name='Link')),
            ],
        ),
    ]
