# Generated by Django 3.2.8 on 2022-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiascad',
            name='autenticidade',
            field=models.BooleanField(default=False, verbose_name='Marque se for verdadeira, desmarque se for falsa'),
        ),
    ]
